### ISSUE TITLE
Please support idea2024.2.1 version

### ISSUE THREAD

**Issue by NoahNyy** [kiberohrannik/Compare-Master#2]
Please support idea2024.2.1 version

**Comment by kiberohrannik** [comment]
> Please support idea2024.2.1 version

Hi, there is new version 1.2.0 available now (till 2024.2.3 and including latest EAP versions).

Thanks for your PR, I will check if there is anything missing from my side and it will be added to the next versions.

**Comment by NoahNyy** [comment]
Ok, Thank you. 
and your plugin is very help for me!
